# Site settings
title: Guillaume Dubeaux, Ph.D.
email: guillaume@dubeaux.me
author: Guillaume Dubeaux
description: My personal website.
url: guillaume.dubeaux.me

# Build settings
permalink: :title/
sass:
  sass_dir: css

# Social icons
show_social_icons: true
github_username: gdubeaux
twitter_username: gdubeaux
linkedin_username: gdubeaux

# plugins
plugins: [jekyll-paginate]
paginate: 10
