# Site settings
title: Guillaume Dubeaux, Ph.D.
email: guillaume@dubeaux.me
author: Guillaume Dubeaux
description: "Post-doctoral EMBO Fellow at UCSD. Born and raised in Paris ğŸ‡«ğŸ‡·. Now living in sunny SoCal â˜€ï¸. Proud father of 2 ğŸ˜."
url: guillaume.dubeaux.me

# Build settings
permalink: :title/
sass:
  sass_dir: css

# Social icons
show_social_icons: true
github_username: gdubeaux
twitter_username: gdubeaux
linkedin_username: gdubeaux

# plugins
plugins: [jekyll-paginate]
paginate: 5
